### ISSUE TITLE
Subscription isn't triggered, although I see the packet data

### ISSUE THREAD

**Issue by fluffynuts** [LadislavBohm/socket.io-client-core#8]
Hi

I'm trying to use `Socket.Io.Client.Core` for the underlying communications of a generic pub/sub service with persistence for messages. The basic usage is:

- client connects
- client subscribes via `/subscribe` with some info (topic, offset, channel)
- client publishes (in the real world, this is another client, of course) to the topic for the channel
- client should receive a `/consume` notification with the message

Now in the test code below, I can see the comms working out - I can see the received packet for `/consume`, but the handler set up with `client.On("/consume")` is never called. I've set up a demonstration repo at https://github.com/fluffynuts/socket-io-core-subscribe-issue . There's a README in there to explain how to reproduce the issue with the provided code.

For the moment, I'm going to have to manually parse `Packet` instances which come into the `OnPacket` event, but it would be really nice if I could use this library as intended.

**Comment by LadislavBohm** [comment]
Thanks for reporting, I will check your repository and let you know what's wrong.

**Comment by LadislavBohm** [comment]
There were number of issues here:
1.  You are not json serializing emitted data on your server (this should be supported by this library)
2.  Same issue happens when you respond to callback with { success: true } so you do not receive any callbacks (ACKs)

For debugging it's a good idea to subscribe to OnError event and/or pass in real logger. I will have to consider specific JSON library dependency to handle message data in a different way. Most likely System.Text.Json.
